### ISSUE TITLE
Accelerometer Component

### ISSUE THREAD

**Issue by roboryman** [roboryman/prototroller#40]
The user may shake, jerk, or otherwise move the controller to provide X, Y, and Z axes acceleration inputs.
![image](https://user-images.githubusercontent.com/6272643/203857172-ed38d314-990e-4671-a84c-c48dd31fc9d5.png)

**Comment by evanzh15** [comment]
Added a LSM6DS3 accelerometer/gyroscope into the master_board.kicad_sch, configured for SPI
