### ISSUE TITLE
Gyroscope Component

### ISSUE THREAD

**Issue by roboryman** [roboryman/prototroller#41]
The gyroscope utilizes measurements of angular velocity, typically tilting the controller is enough to register a reading.
![image](https://user-images.githubusercontent.com/6272643/203857327-2059c563-b401-4a40-b129-b72b7c912698.png)

**Comment by evanzh15** [comment]
Added a LSM6DS3 accelerometer/gyroscope into the master_board.kicad_sch, configured for SPI
