### ISSUE TITLE
Design Master Crystal Oscillator Block 

### ISSUE THREAD

**Issue by roboryman** [roboryman/prototroller#50]
Our integrated board design may require an external crystal oscillator for a stable frequency source to the master RP2040. While the RP2040 has an internal oscillator, they recommend feeding the clock from an external oscillator. So, step 1 is determining if we can use the internal crystal with the high frequencies we will likely need for SPI (>= 10 Mbps), step 2 is picking a crystal oscillator that fits those constraints, and step 3 is designing around the selected part.

**Comment by evanzh15** [comment]
Find appropriate Crystal Oscillator component with footprint.
