### ISSUE TITLE
Design Master Rescan Block

### ISSUE THREAD

**Issue by roboryman** [roboryman/prototroller#55]
The user will need to press a rescan button to indicate they have connected new modules, from which the master attempts an identification handshake on all possible chip selects. Design the module for this (simple GPIO and pull-up resistor, but we may have to creatively place this on the Prototroller itself).

**Comment by evanzh15** [comment]
Created a section in master_board.kicad_sch that pulls up signal RESET, and connects it to a tactile switch. #
