### ISSUE TITLE
Rev-B Master and Module Board Design

### ISSUE THREAD

**Issue by evanzh15** [roboryman/prototroller#73]
Make modifications to the Rev-A Master and Module PCBs and Schematics to adjust issues and design flaws in the original boards.

Modify the following (but not limited to):

Master Board RevB:
- [x] Fix 4x16 decoder footprint
- [x] Keep flash pull-up at 10k, change 10k pull-up for BOOTSEL to 1k
- [x] Change the haptic 1x1 male header footprints to a single 1x4 male header footprint
- [x] Change the SWD connector to a ~1x4 male header footprint instead of a receptacle (SWDIO, SWCLK, RESET_N, GND)~ JST-SH BM03B-SRSS-TB receptacle for use with the official debugger
- [x] Add test points at bottom of board for SPI lines, VCC, GND (for measuring power distribution)
- [x] Add test points to GPIOs where possible
- [x] Add test points for chip selects coming from decoder
- [x] Module indicators on front silkscreen
- [x] _Maybe_: Modify pogo connector to not have VCC, GND next to each other (req. module board change)
- [ ] ...

Module Board RevB:
- [x] Add status LED and supporting circuitry
- [x] Get rid of BOOTSEL pad and associated 10k
- [x] Keep flash pull-up at 10k
- [x] Get rid of GND pin near SWD pins
- [x] Assign nets to the 2 1x2 female headers (rows are unconstrained)
- [x] Move SWD pins up, if at all possible
- [x] Add general test points, if at all possible
- [ ] ...

**Comment by evanzh15** [comment]
[https://github.com/roboryman/prototroller/tree/rev-b](url)

**Comment by roboryman** [comment]
Added a bit. For both boards we should keep the 10k on the QSPI_NSS flash nets since our boards work great with them currently. We need to decide on what nets we are going to assign to the 4 extra pins on the mod boards.
